# requiring the environment of Ruby 2.3.x
image: ruby:2.3

# add bundle cache to 'vendor' for speeding up builds
cache:
  paths: 
    - vendor/

before_script:
  - bundle install --path vendor

# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
    - cd public
    - mkdir -p /.well-known/acme-challenge
    - cd .well-known
    - cd acme-challenge
    - printf "%s" JrC7khHB8r2s4DiNNJXvETNod8uQ2suyql5pDV7b3Bk.SxPcxP8A1yLaeXm8nl8Zht3A5cRQmdQI8RE-p6UDEwA > JrC7khHB8r2s4DiNNJXvETNod8uQ2suyql5pDV7b3Bk
  artifacts:
    paths:
      - public
  only:
    - master # this job will affect only the 'master' branch
